name: debounce
description: Debounce demo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  get:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  flutter_web3: ^2.1.9
  web3dart:
  ethereum_addresses: 1.0.2

  shared_preferences: ^2.0.8
  http: ^0.13.3
  universal_html: ^2.0.8

  cupertino_icons: ^1.0.2
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/